<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite errors="1" failures="0" tests="1" skipped="0" name=".Users.krunalkathikar.Downloads.iStyle.test.splash_widget" timestamp="2025-02-05T12:02:02">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.krunalkathikar.Downloads.iStyle.test.splash_widget" name="When Splash Screen Open" time="0.365">
      <error message="1 error, see stacktrace for details">Error:

Test failed. See exception logs above.
The test description was: When Splash Screen Open</error>
      <system-out>══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: &lt;false>
  Actual: &lt;true>

When the exception was thrown, this was the stack:
#4      main.&lt;anonymous closure> (file:///Users/krunalkathikar/Downloads/iStyle/test/splash_widget_test.dart:21:5)
&lt;asynchronous suspension>
#5      testWidgets.&lt;anonymous closure>.&lt;anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
&lt;asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
&lt;asynchronous suspension>
&lt;asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/krunalkathikar/Downloads/iStyle/test/splash_widget_test.dart line 21
The test description was:
  When Splash Screen Open
════════════════════════════════════════════════════════════════════════════════════════════════════</system-out>
    </testcase>
  </testsuite>
</testsuites>